spring:
  thymeleaf:
    cache: false
    check-template: false
    mode: LEGACYHTML5
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
server:
  port: 8086